/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 cat.gltf --transform 
Files: cat.gltf [875.81KB] > C:\Users\Naysa Chopra\Downloads\cat_box_meme\cat-transformed.glb [55.83KB] (94%)
Author: Adrian.Alexis.Liberato (https://sketchfab.com/Adrian.Alexis.Liberato)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cat-box-meme-107d19cd699b45a5a7683aa4f9ce0d0d
Title: Cat box meme
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/cat-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.Material__27} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/cat-transformed.glb')
